copyright: Copyright &copy; 2020 hotio
edit_uri: ''

extra:
  social:
  - icon: fontawesome/brands/discord
    link: 'https://hotio.dev/discord'
    name: Discord
  - icon: fontawesome/brands/docker
    link: 'https://hub.docker.com/u/hotio'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://github.com/docker-hotio'
    name: GitHub

extra_css:
  - stylesheets/extra.css

plugins:
- search
- redirects:
    redirect_maps:
      discord.md: 'https://discord.gg/3SnkuKp'
      docker.md: 'https://hub.docker.com/u/hotio'
      github.md: 'https://github.com/docker-hotio'

repo_name: hotio
repo_url: https://github.com/docker-hotio
site_author: hotio
site_description: Documentation to get the containers running
site_name: hotio.dev
site_url: https://hotio.dev

theme:
  favicon: img/favicon.ico
  features:
    - navigation.instant
  language: en
  logo: img/logo.png
  name: material

nav:
- Home: index.md
- Images:
  - images/hd-idle.md
  - images/radarr.md
