name: build-pages

on:
  push:
    paths:
    - 'source/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Build site
      run: |
        ./gen-menu.py
        docker run --rm -v ${PWD}/source:/docs -v ${PWD}/docs:/output squidfunk/mkdocs-material build -c -d /output
        touch ${PWD}/docs/.nojekyll
        echo "hotio.dev" > ${PWD}/docs/CNAME

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4.5.1
      with:
        commit_message: Update Website
