name: push-readme

on:
  push:
    paths:
    - 'source/docs/containers/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      id: files
    - name: Push README
      env:
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        git config --global user.email "github-action@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        for file in ${{ steps.files.outputs.added_modified }}; do
          readme=$(basename ${file//.md/})
          git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/docker-${readme}.git
          cp ${PWD}/source/docs/containers/${readme}.md ${PWD}/docker-${readme}/README.md
          cd docker-${readme} || exit 1
          git add README.md
          if git commit -m "Synced README with hotio.dev"; then
            git push
          fi
          docker run -v $PWD:/workspace -e DOCKERHUB_USERNAME="${DOCKER_USER}" -e DOCKERHUB_PASSWORD="${DOCKER_PASS}" -e DOCKERHUB_REPOSITORY="${DOCKER_USER}/${readme}" -e README_FILEPATH='/workspace/README.md' -e SHORT_DESCRIPTION="Visit https://hotio.dev for more information." peterevans/dockerhub-description:2
        done
